# Generated by Django 3.2.5 on 2021-10-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_app1s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_grad', models.CharField(default='60', max_length=10)),
                ('g', models.CharField(default='9.98', max_length=10)),
                ('l', models.CharField(default='0.50', max_length=10)),
                ('m', models.CharField(default='0.2367', max_length=10)),
                ('rK', models.CharField(default='0.02', max_length=10)),
                ('deltaR', models.CharField(default='0.07', max_length=10)),
                ('anzahlT', models.CharField(default='3', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('figure', models.ImageField(blank=True, default='pendulum/pen_show', upload_to='pendulum')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_app1s.entry')),
            ],
        ),
    ]
