# Generated by Django 3.2.5 on 2021-10-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0002_auto_20211027_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penshow',
            name='video_t',
        ),
    ]
