# Generated by Django 3.2.5 on 2021-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0004_penshow_video_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penshow',
            name='video_t',
        ),
        migrations.AddField(
            model_name='penshow',
            name='video_v',
            field=models.FileField(blank=True, default='pendulum/anim_v', upload_to='pendulum'),
        ),
    ]
