# Generated by Django 3.2.5 on 2021-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0005_auto_20211028_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penshow',
            name='anzahlT',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='3', max_length=10),
        ),
    ]
