# Generated by Django 3.2.5 on 2021-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0006_alter_penshow_anzahlt'),
    ]

    operations = [
        migrations.AddField(
            model_name='penshow',
            name='video_a',
            field=models.FileField(blank=True, default='pendulum/anim_a', upload_to='pendulum'),
        ),
        migrations.AddField(
            model_name='penshow',
            name='video_b',
            field=models.FileField(blank=True, default='pendulum/anim_b', upload_to='pendulum'),
        ),
    ]
