# Generated by Django 3.2.5 on 2021-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0008_auto_20211111_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='penshow',
            name='x_max',
            field=models.CharField(default='3.1', max_length=10),
        ),
        migrations.AlterField(
            model_name='penshow',
            name='alpha_grad',
            field=models.CharField(choices=[('10', '10'), ('30', '30'), ('45', '45'), ('60', '60'), ('75', '75'), ('90', '90')], default='60', max_length=10),
        ),
        migrations.AlterField(
            model_name='penshow',
            name='deltaR',
            field=models.CharField(choices=[('0.09', 'Luftwiderstand-Koeffizient bei dem normalen Luftdruck'), ('0.0009', 'Luftwiderstand-Koeffizient bei dem sehr kleinen Luftdruck'), ('0.009', 'Luftwiderstand-Koeffizient bei dem kleinen Luftdruck'), ('0.9', 'Luftwiderstand-Koeffizient bei dem großen Luftdruck'), ('9.0', 'Luftwiderstand-Koeffizient bei dem sehr großen Luftdruck')], default='0.07', max_length=10),
        ),
        migrations.AlterField(
            model_name='penshow',
            name='g',
            field=models.CharField(choices=[('9.81', '9,81 Erde'), ('1.62', '1,62 Mond'), ('274.00', '274,00 Sonne'), ('3.70', '3,70 Merkur'), ('8.87', '8,87 Venus'), ('3.72', '3,72 Mars'), ('24.79', '24,79 Jupiter'), ('10.44', '10,44 Saturn'), ('8.87', '8,87 Uranus'), ('11.15', '11,15 Neptun'), ('0.62', '0,62 Pluto'), ('0.000167', '0,000167 Komet Tschurjumow-Gerassimenko')], default='9.98', max_length=10),
        ),
        migrations.AlterField(
            model_name='penshow',
            name='l',
            field=models.CharField(choices=[('0.25', '25 cm'), ('0.05', '5 cm'), ('0.1', '10 cm'), ('0.5', '50 cm'), ('1.0', '1 m'), ('1.5', '1,5 m'), ('2.0', '2 m'), ('5.0', '5 m'), ('10.0', '10 m'), ('20.0', '20 m')], default='0.25', max_length=10),
        ),
        migrations.AlterField(
            model_name='penshow',
            name='m',
            field=models.CharField(choices=[('0.2367', '236,7 g Stahlkugel'), ('0.02367', '23,67 g Hartholzkugel'), ('0.5744', '574,4 g Urankugel')], default='0.2367', max_length=10),
        ),
    ]
