# Generated by Django 3.2.5 on 2021-11-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0009_auto_20211114_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penshow',
            name='l',
            field=models.CharField(choices=[('0.5', '50 cm'), ('0.05', '5 cm'), ('0.1', '10 cm'), ('0.25', '25 cm'), ('1.0', '1 m'), ('1.5', '1,5 m'), ('2.0', '2 m'), ('5.0', '5 m'), ('10.0', '10 m'), ('20.0', '20 m')], default='0.25', max_length=10),
        ),
    ]
