# Generated by Django 3.2.5 on 2023-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendulum_show', '0010_alter_penshow_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penshow',
            name='m',
            field=models.CharField(choices=[('0.2367', '236,70 g Stahlkugel'), ('0.02367', '23,67 g Hartholzkugel'), ('0.5744', '574,40 g Urankugel')], default='0.2367', max_length=10),
        ),
    ]
