# Generated by Django 3.2.5 on 2021-10-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_app1s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_points', models.CharField(default='1000', max_length=50)),
                ('x_distance', models.CharField(default='0, 1, 2, 3, 4', max_length=50)),
                ('y_distance', models.CharField(default='0, 1, 2, 3, 4', max_length=50)),
                ('dot_marker', models.CharField(choices=[('.', 'Punkt'), ('o', 'Kreis'), ('s', 'Quadrat'), ('^', 'Dreieck ^'), ('v', 'Dreieck v'), ('8', 'Octagon'), ('D', 'Diamant'), ('d', 'Rombe'), ('(4,1)', 'Stern 4'), ('*', 'Stern 5'), ('(7,1)', 'Stern 7'), ('(8,1)', 'Stern 8'), ('(9,1)', 'Stern 9'), ('(5,2)', 'Schneeflocke 5'), ('(6,2)', 'Schneeflocke 6'), ('(7,2)', 'Schneeflocke 7'), ('(8,2)', 'Schneeflocke 8'), ('(9,2)', 'Schneeflocke 9')], default='.', max_length=10)),
                ('dot_size', models.CharField(default='5.0', max_length=10)),
                ('dot_alpha', models.CharField(default='1.0', max_length=10)),
                ('dot_color', models.CharField(choices=[('white', 'white'), ('whitesmoke', 'whitesmoke'), ('lightgray', 'lightgray'), ('gray', 'gray'), ('dimgray', 'dimgray'), ('black', 'black'), ('mistyrose', 'mistyrose'), ('lightcoral', 'lightcoral'), ('coral', 'coral'), ('red', 'red'), ('brown', 'brown'), ('maroon', 'maroon'), ('beige', 'beige'), ('yellow', 'yellow'), ('gold', 'gold'), ('orange', 'orange'), ('chocolate', 'chocolate'), ('sienna', 'sienna'), ('ivory', 'ivory'), ('lightgreen', 'lightgreen'), ('lime', 'lime'), ('green', 'green'), ('darkgreen', 'darkgreen'), ('olive', 'olive'), ('azure', 'azure'), ('aqua', 'aqua'), ('turquoise', 'turquoise'), ('teal', 'teal'), ('darkslategray', 'darkslategray'), ('lightblue', 'lightblue'), ('deepskyblue', 'deepskyblue'), ('cornflowerblue', 'cornflowerblue'), ('royalblue', 'royalblue'), ('blue', 'blue'), ('steelblue', 'steelblue'), ('navy', 'navy'), ('darkslateblue', 'darkslateblue'), ('lavenderblush', 'lavenderblush'), ('pink', 'pink'), ('plum', 'plum'), ('violet', 'violet'), ('purple', 'purple'), ('darkorchid', 'darkorchid'), ('indigo', 'indigo')], default='white', max_length=50)),
                ('ax_color', models.CharField(choices=[('white', 'white'), ('whitesmoke', 'whitesmoke'), ('lightgray', 'lightgray'), ('gray', 'gray'), ('dimgray', 'dimgray'), ('black', 'black'), ('mistyrose', 'mistyrose'), ('lightcoral', 'lightcoral'), ('coral', 'coral'), ('red', 'red'), ('brown', 'brown'), ('maroon', 'maroon'), ('beige', 'beige'), ('yellow', 'yellow'), ('gold', 'gold'), ('orange', 'orange'), ('chocolate', 'chocolate'), ('sienna', 'sienna'), ('ivory', 'ivory'), ('lightgreen', 'lightgreen'), ('lime', 'lime'), ('green', 'green'), ('darkgreen', 'darkgreen'), ('olive', 'olive'), ('azure', 'azure'), ('aqua', 'aqua'), ('turquoise', 'turquoise'), ('teal', 'teal'), ('darkslategray', 'darkslategray'), ('lightblue', 'lightblue'), ('deepskyblue', 'deepskyblue'), ('cornflowerblue', 'cornflowerblue'), ('royalblue', 'royalblue'), ('blue', 'blue'), ('steelblue', 'steelblue'), ('navy', 'navy'), ('darkslateblue', 'darkslateblue'), ('lavenderblush', 'lavenderblush'), ('pink', 'pink'), ('plum', 'plum'), ('violet', 'violet'), ('purple', 'purple'), ('darkorchid', 'darkorchid'), ('indigo', 'indigo')], default='ivory', max_length=50)),
                ('c_point_number', models.CharField(default='range(rw.num_points)', max_length=50)),
                ('dot_cmap', models.CharField(choices=[('n', 'kein Farbverlauf'), ('tab10', 'tab10'), ('tab20', 'tab20'), ('tab20b', 'tab20b'), ('tab20c', 'tab20c'), ('Greys', 'Greys'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Reds', 'Reds'), ('Purples', 'Purples'), ('Oranges', 'Oranges'), ('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], default='Purples', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('figure', models.ImageField(blank=True, default='rwvisual/rw_visual', upload_to='rwvisual')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_app1s.entry')),
            ],
        ),
    ]
