# Generated by Django 3.2.5 on 2021-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0002_auto_20211031_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwvisual',
            name='x_distance',
            field=models.CharField(default='0 1 2 3 4', max_length=50),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='y_distance',
            field=models.CharField(default='0 1 2 3 4', max_length=50),
        ),
    ]
