# Generated by Django 3.2.5 on 2021-11-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0003_auto_20211104_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwvisual',
            name='x_values',
            field=models.CharField(default='0 1 2 3 4', max_length=50000),
        ),
        migrations.AddField(
            model_name='rwvisual',
            name='y_values',
            field=models.CharField(default='0 1 2 3 4', max_length=50000),
        ),
    ]
