# Generated by Django 3.2.5 on 2021-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0004_auto_20211104_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwvisual',
            name='num_points',
            field=models.CharField(choices=[('10', '10'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('250', '250'), ('500', '500'), ('750', '750'), ('1000', '1000'), ('2500', '2500'), ('5000', '5000'), ('7500', '7500'), ('10000', '10000')], default='1000', max_length=50),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='x_distance',
            field=models.CharField(choices=[('0 1 2 3 4 5', '0 1 2 3 4 5'), ('0 1 1 1 3 4', '0 1 1 1 3 4'), ('0 1 3 4 4 4', '0 1 3 4 4 4')], default='0 1 2 3 4', max_length=50),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='y_distance',
            field=models.CharField(choices=[('0 1 2 3 4 5', '0 1 2 3 4 5'), ('0 1 1 1 3 4', '0 1 1 1 3 4'), ('0 1 3 4 4 4', '0 1 3 4 4 4')], default='0 1 2 3 4', max_length=50),
        ),
    ]
