# Generated by Django 3.2.5 on 2021-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0005_auto_20211105_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwvisual',
            name='video_b1',
            field=models.FileField(blank=True, default='rwvisual/rw_visual_b1', upload_to='rwvisual'),
        ),
        migrations.AddField(
            model_name='rwvisual',
            name='video_b2',
            field=models.FileField(blank=True, default='rwvisual/rw_visual_b2', upload_to='rwvisual'),
        ),
    ]
