# Generated by Django 3.2.5 on 2021-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0008_alter_rwvisual_dot_cmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwvisual',
            name='dot_alpha',
            field=models.CharField(choices=[('0.1', '0,1'), ('0.2', '0,2'), ('0.3', '0,3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0,7'), ('0.8', '0,8'), ('0.9', '0,9'), ('1.0', '1')], default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='dot_size',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('10', '10'), ('50', '50'), ('100', '100'), ('250', '250'), ('250', '250'), ('500', '500'), ('750', '750'), ('1000', '1000'), ('2500', '2500'), ('5000', '5000'), ('7500', '7500'), ('10000', '10000')], default='5.0', max_length=10),
        ),
    ]
