# Generated by Django 3.2.5 on 2021-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0010_alter_rwvisual_dot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwvisual',
            name='dot_alpha',
            field=models.CharField(choices=[('0.1', '0,1'), ('0.2', '0,2'), ('0.3', '0,3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0,6'), ('0.7', '0,7'), ('0.8', '0,8'), ('0.9', '0,9'), ('1.0', '1')], default='1.0', max_length=10),
        ),
    ]
