# Generated by Django 3.2.5 on 2021-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0011_alter_rwvisual_dot_alpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwvisual',
            name='dot_alpha_v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rwvisual',
            name='dot_size_v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rwvisual',
            name='point_numbers_random',
            field=models.CharField(default='0 1 2 3 4', max_length=150000),
        ),
    ]
