# Generated by Django 3.2.5 on 2023-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_visual', '0014_alter_rwvisual_dot_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwvisual',
            name='point_numbers_random',
            field=models.CharField(default='0 1 2 3 4', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='x_values',
            field=models.CharField(default='0 1 2 3 4', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='rwvisual',
            name='y_values',
            field=models.CharField(default='0 1 2 3 4', max_length=1000000),
        ),
    ]
