# Generated by Django 3.2.5 on 2021-10-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_app1s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnumShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnumInput', models.CharField(default='n.a.', max_length=50)),
                ('precInputDef', models.CharField(default=4, max_length=2)),
                ('dnumDIN', models.CharField(default='n.a.', max_length=50)),
                ('dnumI', models.CharField(default='n.a.', max_length=50)),
                ('dnumS', models.CharField(default='n.a.', max_length=100)),
                ('dnumM', models.CharField(default='n.a.', max_length=50)),
                ('dnumP', models.CharField(default='n.a.', max_length=10)),
                ('dnumMshift', models.CharField(default='n.a.', max_length=50)),
                ('dnumPshift', models.CharField(default='n.a.', max_length=10)),
                ('dnumSignum', models.BooleanField(default=False)),
                ('dnumAbb', models.CharField(default='n.a.', max_length=4)),
                ('dnumPrefix', models.CharField(default='n.a.', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, default='dnumray/dnum_ray', upload_to='dnumray')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_app1s.entry')),
            ],
        ),
    ]
